### ISSUE TITLE
CC0

### ISSUE THREAD

**Issue by callumacrae** [bcherny/winston-bugsnag#3]
Hello!

Is there any reason you're releasing this project under CC0? It means we can't use your project.

https://opensource.org/faq#cc-zero

I see that you've been releasing your more recent libraries using the MIT license: it would be really great if you were willing to rerelease this library using the MIT license!

Thank you :)

**Comment by bcherny** [comment]
Sure - released v2.0.0 under MIT.

**Comment by callumacrae** [comment]
Thank you! 🎉
